-- Create companies table
CREATE TABLE companies (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  country VARCHAR(100) NOT NULL,
  industry VARCHAR(100),
  website VARCHAR(255),
  logo_url VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster searches
CREATE INDEX idx_companies_name ON companies USING gin(to_tsvector('english', name));
CREATE INDEX idx_companies_country ON companies(country);

-- Enable RLS
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Companies are viewable by everyone" ON companies
  FOR SELECT USING (true);

CREATE POLICY "Companies can be created by authenticated users" ON companies
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Insert popular US companies
INSERT INTO companies (name, country, industry, website) VALUES
-- Technology
('Apple', 'USA', 'Technology', 'https://www.apple.com'),
('Google', 'USA', 'Technology', 'https://www.google.com'),
('Microsoft', 'USA', 'Technology', 'https://www.microsoft.com'),
('Amazon', 'USA', 'Technology', 'https://www.amazon.com'),
('Meta', 'USA', 'Technology', 'https://www.meta.com'),
('Netflix', 'USA', 'Technology', 'https://www.netflix.com'),
('Tesla', 'USA', 'Technology', 'https://www.tesla.com'),
('NVIDIA', 'USA', 'Technology', 'https://www.nvidia.com'),
('Salesforce', 'USA', 'Technology', 'https://www.salesforce.com'),
('Adobe', 'USA', 'Technology', 'https://www.adobe.com'),
('Oracle', 'USA', 'Technology', 'https://www.oracle.com'),
('Intel', 'USA', 'Technology', 'https://www.intel.com'),
('IBM', 'USA', 'Technology', 'https://www.ibm.com'),
('Cisco', 'USA', 'Technology', 'https://www.cisco.com'),
('PayPal', 'USA', 'Technology', 'https://www.paypal.com'),
('Uber', 'USA', 'Technology', 'https://www.uber.com'),
('Airbnb', 'USA', 'Technology', 'https://www.airbnb.com'),
('Spotify', 'USA', 'Technology', 'https://www.spotify.com'),
('Twitter', 'USA', 'Technology', 'https://www.twitter.com'),
('LinkedIn', 'USA', 'Technology', 'https://www.linkedin.com'),
('GitHub', 'USA', 'Technology', 'https://www.github.com'),
('Slack', 'USA', 'Technology', 'https://www.slack.com'),
('Zoom', 'USA', 'Technology', 'https://www.zoom.us'),
('Dropbox', 'USA', 'Technology', 'https://www.dropbox.com'),
('Shopify', 'USA', 'Technology', 'https://www.shopify.com'),
('Square', 'USA', 'Technology', 'https://www.square.com'),
('Stripe', 'USA', 'Technology', 'https://www.stripe.com'),
('Palantir', 'USA', 'Technology', 'https://www.palantir.com'),
('Snowflake', 'USA', 'Technology', 'https://www.snowflake.com'),
('Datadog', 'USA', 'Technology', 'https://www.datadog.com'),
('MongoDB', 'USA', 'Technology', 'https://www.mongodb.com'),
('Atlassian', 'USA', 'Technology', 'https://www.atlassian.com'),
('ServiceNow', 'USA', 'Technology', 'https://www.servicenow.com'),
('Workday', 'USA', 'Technology', 'https://www.workday.com'),
('Splunk', 'USA', 'Technology', 'https://www.splunk.com'),
('VMware', 'USA', 'Technology', 'https://www.vmware.com'),
('Autodesk', 'USA', 'Technology', 'https://www.autodesk.com'),
('Intuit', 'USA', 'Technology', 'https://www.intuit.com'),
('Electronic Arts', 'USA', 'Technology', 'https://www.ea.com'),
('Activision Blizzard', 'USA', 'Technology', 'https://www.activisionblizzard.com'),
('Take-Two Interactive', 'USA', 'Technology', 'https://www.take2games.com'),
('Unity Technologies', 'USA', 'Technology', 'https://www.unity.com'),
('Roblox', 'USA', 'Technology', 'https://www.roblox.com'),
('Snap Inc', 'USA', 'Technology', 'https://www.snap.com'),
('Pinterest', 'USA', 'Technology', 'https://www.pinterest.com'),
('Reddit', 'USA', 'Technology', 'https://www.reddit.com'),
('Discord', 'USA', 'Technology', 'https://www.discord.com'),
('Twitch', 'USA', 'Technology', 'https://www.twitch.tv'),
('TikTok', 'USA', 'Technology', 'https://www.tiktok.com'),
('ByteDance', 'USA', 'Technology', 'https://www.bytedance.com'),

-- Finance
('JPMorgan Chase', 'USA', 'Finance', 'https://www.jpmorganchase.com'),
('Bank of America', 'USA', 'Finance', 'https://www.bankofamerica.com'),
('Wells Fargo', 'USA', 'Finance', 'https://www.wellsfargo.com'),
('Goldman Sachs', 'USA', 'Finance', 'https://www.goldmansachs.com'),
('Morgan Stanley', 'USA', 'Finance', 'https://www.morganstanley.com'),
('Citigroup', 'USA', 'Finance', 'https://www.citigroup.com'),
('American Express', 'USA', 'Finance', 'https://www.americanexpress.com'),
('Visa', 'USA', 'Finance', 'https://www.visa.com'),
('Mastercard', 'USA', 'Finance', 'https://www.mastercard.com'),
('BlackRock', 'USA', 'Finance', 'https://www.blackrock.com'),
('Charles Schwab', 'USA', 'Finance', 'https://www.schwab.com'),
('Fidelity Investments', 'USA', 'Finance', 'https://www.fidelity.com'),
('State Street', 'USA', 'Finance', 'https://www.statestreet.com'),
('PNC Financial', 'USA', 'Finance', 'https://www.pnc.com'),
('US Bancorp', 'USA', 'Finance', 'https://www.usbank.com'),

-- Healthcare
('Johnson & Johnson', 'USA', 'Healthcare', 'https://www.jnj.com'),
('Pfizer', 'USA', 'Healthcare', 'https://www.pfizer.com'),
('UnitedHealth Group', 'USA', 'Healthcare', 'https://www.unitedhealthgroup.com'),
('Eli Lilly', 'USA', 'Healthcare', 'https://www.lilly.com'),
('Merck', 'USA', 'Healthcare', 'https://www.merck.com'),
('Abbott Laboratories', 'USA', 'Healthcare', 'https://www.abbott.com'),
('Amgen', 'USA', 'Healthcare', 'https://www.amgen.com'),
('Gilead Sciences', 'USA', 'Healthcare', 'https://www.gilead.com'),
('Bristol-Myers Squibb', 'USA', 'Healthcare', 'https://www.bms.com'),
('Moderna', 'USA', 'Healthcare', 'https://www.modernatx.com'),
('Regeneron', 'USA', 'Healthcare', 'https://www.regeneron.com'),
('Biogen', 'USA', 'Healthcare', 'https://www.biogen.com'),
('Vertex Pharmaceuticals', 'USA', 'Healthcare', 'https://www.vrtx.com'),
('Illumina', 'USA', 'Healthcare', 'https://www.illumina.com'),
('Danaher', 'USA', 'Healthcare', 'https://www.danaher.com'),

-- Consumer Goods
('Procter & Gamble', 'USA', 'Consumer Goods', 'https://www.pg.com'),
('Coca-Cola', 'USA', 'Consumer Goods', 'https://www.coca-cola.com'),
('PepsiCo', 'USA', 'Consumer Goods', 'https://www.pepsico.com'),
('Nike', 'USA', 'Consumer Goods', 'https://www.nike.com'),
('McDonald''s', 'USA', 'Consumer Goods', 'https://www.mcdonalds.com'),
('Starbucks', 'USA', 'Consumer Goods', 'https://www.starbucks.com'),
('Walmart', 'USA', 'Consumer Goods', 'https://www.walmart.com'),
('Target', 'USA', 'Consumer Goods', 'https://www.target.com'),
('Home Depot', 'USA', 'Consumer Goods', 'https://www.homedepot.com'),
('Costco', 'USA', 'Consumer Goods', 'https://www.costco.com'),
('Disney', 'USA', 'Consumer Goods', 'https://www.disney.com'),
('Netflix', 'USA', 'Consumer Goods', 'https://www.netflix.com'),
('Verizon', 'USA', 'Consumer Goods', 'https://www.verizon.com'),
('AT&T', 'USA', 'Consumer Goods', 'https://www.att.com'),
('Comcast', 'USA', 'Consumer Goods', 'https://www.comcast.com'),

-- Industrial
('General Electric', 'USA', 'Industrial', 'https://www.ge.com'),
('Boeing', 'USA', 'Industrial', 'https://www.boeing.com'),
('Caterpillar', 'USA', 'Industrial', 'https://www.caterpillar.com'),
('3M', 'USA', 'Industrial', 'https://www.3m.com'),
('Honeywell', 'USA', 'Industrial', 'https://www.honeywell.com'),
('United Technologies', 'USA', 'Industrial', 'https://www.utc.com'),
('Lockheed Martin', 'USA', 'Industrial', 'https://www.lockheedmartin.com'),
('Raytheon', 'USA', 'Industrial', 'https://www.raytheon.com'),
('General Motors', 'USA', 'Industrial', 'https://www.gm.com'),
('Ford', 'USA', 'Industrial', 'https://www.ford.com'),
('Chevron', 'USA', 'Industrial', 'https://www.chevron.com'),
('ExxonMobil', 'USA', 'Industrial', 'https://www.exxonmobil.com'),
('ConocoPhillips', 'USA', 'Industrial', 'https://www.conocophillips.com'),
('Valero Energy', 'USA', 'Industrial', 'https://www.valero.com'),
('Phillips 66', 'USA', 'Industrial', 'https://www.phillips66.com'),

-- Insert popular Finnish companies
-- Technology
('Nokia', 'Finland', 'Technology', 'https://www.nokia.com'),
('Rovio Entertainment', 'Finland', 'Technology', 'https://www.rovio.com'),
('Supercell', 'Finland', 'Technology', 'https://www.supercell.com'),
('Remedy Entertainment', 'Finland', 'Technology', 'https://www.remedygames.com'),
('Housemarque', 'Finland', 'Technology', 'https://www.housemarque.com'),
('Fingersoft', 'Finland', 'Technology', 'https://www.fingersoft.net'),
('Seriously Digital Entertainment', 'Finland', 'Technology', 'https://www.seriously.com'),
('Small Giant Games', 'Finland', 'Technology', 'https://www.smallgiantgames.com'),
('Next Games', 'Finland', 'Technology', 'https://www.nextgames.com'),
('Frogmind', 'Finland', 'Technology', 'https://www.frogmindgames.com'),
('RedLynx', 'Finland', 'Technology', 'https://www.redlynx.com'),
('Bugbear Entertainment', 'Finland', 'Technology', 'https://www.bugbear.fi'),
('HypeHype', 'Finland', 'Technology', 'https://www.hypehype.com'),
('Metacore', 'Finland', 'Technology', 'https://www.metacoregames.com'),
('Traplight', 'Finland', 'Technology', 'https://www.traplight.com'),
('Frozenbyte', 'Finland', 'Technology', 'https://www.frozenbyte.com'),
('Colossal Order', 'Finland', 'Technology', 'https://www.colossalorder.fi'),
('Housemarque', 'Finland', 'Technology', 'https://www.housemarque.com'),
('Futuremark', 'Finland', 'Technology', 'https://www.futuremark.com'),
('Rightware', 'Finland', 'Technology', 'https://www.rightware.com'),
('Basemark', 'Finland', 'Technology', 'https://www.basemark.com'),
('Umbra', 'Finland', 'Technology', 'https://www.umbra3d.com'),
('Intel Finland', 'Finland', 'Technology', 'https://www.intel.fi'),
('Google Finland', 'Finland', 'Technology', 'https://www.google.fi'),
('Microsoft Finland', 'Finland', 'Technology', 'https://www.microsoft.fi'),
('Amazon Finland', 'Finland', 'Technology', 'https://www.amazon.fi'),
('Meta Finland', 'Finland', 'Technology', 'https://www.meta.fi'),
('Apple Finland', 'Finland', 'Technology', 'https://www.apple.fi'),
('Netflix Finland', 'Finland', 'Technology', 'https://www.netflix.fi'),
('Spotify Finland', 'Finland', 'Technology', 'https://www.spotify.fi'),
('Slack Finland', 'Finland', 'Technology', 'https://www.slack.fi'),
('Zoom Finland', 'Finland', 'Technology', 'https://www.zoom.fi'),
('Salesforce Finland', 'Finland', 'Technology', 'https://www.salesforce.fi'),
('Adobe Finland', 'Finland', 'Technology', 'https://www.adobe.fi'),
('Oracle Finland', 'Finland', 'Technology', 'https://www.oracle.fi'),
('IBM Finland', 'Finland', 'Technology', 'https://www.ibm.fi'),
('Cisco Finland', 'Finland', 'Technology', 'https://www.cisco.fi'),
('VMware Finland', 'Finland', 'Technology', 'https://www.vmware.fi'),
('Autodesk Finland', 'Finland', 'Technology', 'https://www.autodesk.fi'),
('Intuit Finland', 'Finland', 'Technology', 'https://www.intuit.fi'),
('Unity Finland', 'Finland', 'Technology', 'https://www.unity.fi'),
('Epic Games Finland', 'Finland', 'Technology', 'https://www.epicgames.fi'),
('Valve Finland', 'Finland', 'Technology', 'https://www.valve.fi'),
('EA Finland', 'Finland', 'Technology', 'https://www.ea.fi'),
('Activision Finland', 'Finland', 'Technology', 'https://www.activision.fi'),
('Ubisoft Finland', 'Finland', 'Technology', 'https://www.ubisoft.fi'),
('Take-Two Finland', 'Finland', 'Technology', 'https://www.take2.fi'),
('Roblox Finland', 'Finland', 'Technology', 'https://www.roblox.fi'),
('Snap Finland', 'Finland', 'Technology', 'https://www.snap.fi'),
('Pinterest Finland', 'Finland', 'Technology', 'https://www.pinterest.fi'),
('Reddit Finland', 'Finland', 'Technology', 'https://www.reddit.fi'),
('Discord Finland', 'Finland', 'Technology', 'https://www.discord.fi'),
('Twitch Finland', 'Finland', 'Technology', 'https://www.twitch.fi'),
('TikTok Finland', 'Finland', 'Technology', 'https://www.tiktok.fi'),
('ByteDance Finland', 'Finland', 'Technology', 'https://www.bytedance.fi'),
('LinkedIn Finland', 'Finland', 'Technology', 'https://www.linkedin.fi'),
('GitHub Finland', 'Finland', 'Technology', 'https://www.github.fi'),
('Dropbox Finland', 'Finland', 'Technology', 'https://www.dropbox.fi'),
('Shopify Finland', 'Finland', 'Technology', 'https://www.shopify.fi'),
('Square Finland', 'Finland', 'Technology', 'https://www.square.fi'),
('Stripe Finland', 'Finland', 'Technology', 'https://www.stripe.fi'),
('Palantir Finland', 'Finland', 'Technology', 'https://www.palantir.fi'),
('Snowflake Finland', 'Finland', 'Technology', 'https://www.snowflake.fi'),
('Datadog Finland', 'Finland', 'Technology', 'https://www.datadog.fi'),
('MongoDB Finland', 'Finland', 'Technology', 'https://www.mongodb.fi'),
('Atlassian Finland', 'Finland', 'Technology', 'https://www.atlassian.fi'),
('ServiceNow Finland', 'Finland', 'Technology', 'https://www.servicenow.fi'),
('Workday Finland', 'Finland', 'Technology', 'https://www.workday.fi'),
('Splunk Finland', 'Finland', 'Technology', 'https://www.splunk.fi'),
('Futuremark Finland', 'Finland', 'Technology', 'https://www.futuremark.fi'),
('Rightware Finland', 'Finland', 'Technology', 'https://www.rightware.fi'),
('Basemark Finland', 'Finland', 'Technology', 'https://www.basemark.fi'),
('Umbra Finland', 'Finland', 'Technology', 'https://www.umbra.fi'),

-- Finance
('Nordea', 'Finland', 'Finance', 'https://www.nordea.fi'),
('OP Financial Group', 'Finland', 'Finance', 'https://www.op.fi'),
('Danske Bank', 'Finland', 'Finance', 'https://www.danskebank.fi'),
('S-Pankki', 'Finland', 'Finance', 'https://www.s-pankki.fi'),
('Aktia Bank', 'Finland', 'Finance', 'https://www.aktia.fi'),
('POP Bank', 'Finland', 'Finance', 'https://www.poppankki.fi'),
('Handelsbanken', 'Finland', 'Finance', 'https://www.handelsbanken.fi'),
('SEB', 'Finland', 'Finance', 'https://www.seb.fi'),
('Swedbank', 'Finland', 'Finance', 'https://www.swedbank.fi'),
('Varma', 'Finland', 'Finance', 'https://www.varma.fi'),
('Ilmarinen', 'Finland', 'Finance', 'https://www.ilmarinen.fi'),
('Elo', 'Finland', 'Finance', 'https://www.elo.fi'),
('Kela', 'Finland', 'Finance', 'https://www.kela.fi'),
('Finnvera', 'Finland', 'Finance', 'https://www.finnvera.fi'),
('Finnfund', 'Finland', 'Finance', 'https://www.finnfund.fi'),

-- Industrial
('Kone', 'Finland', 'Industrial', 'https://www.kone.com'),
('Wärtsilä', 'Finland', 'Industrial', 'https://www.wartsila.com'),
('Metso Outotec', 'Finland', 'Industrial', 'https://www.mogroup.com'),
('Valmet', 'Finland', 'Industrial', 'https://www.valmet.com'),
('Cargotec', 'Finland', 'Industrial', 'https://www.cargotec.com'),
('Kemira', 'Finland', 'Industrial', 'https://www.kemira.com'),
('Neste', 'Finland', 'Industrial', 'https://www.neste.com'),
('UPM', 'Finland', 'Industrial', 'https://www.upm.com'),
('Stora Enso', 'Finland', 'Industrial', 'https://www.storaenso.com'),
('Metsä Group', 'Finland', 'Industrial', 'https://www.metsagroup.com'),
('Fortum', 'Finland', 'Industrial', 'https://www.fortum.com'),
('Helen', 'Finland', 'Industrial', 'https://www.helen.fi'),
('Vattenfall Finland', 'Finland', 'Industrial', 'https://www.vattenfall.fi'),
('Gasum', 'Finland', 'Industrial', 'https://www.gasum.fi'),
('Neste Finland', 'Finland', 'Industrial', 'https://www.neste.fi'),

-- Consumer Goods
('S Group', 'Finland', 'Consumer Goods', 'https://www.s-kanava.fi'),
('K Group', 'Finland', 'Consumer Goods', 'https://www.kesko.fi'),
('Lidl Finland', 'Finland', 'Consumer Goods', 'https://www.lidl.fi'),
('Tokmanni', 'Finland', 'Consumer Goods', 'https://www.tokmanni.fi'),
('Verkkokauppa.com', 'Finland', 'Consumer Goods', 'https://www.verkkokauppa.com'),
('Gigantti', 'Finland', 'Consumer Goods', 'https://www.gigantti.fi'),
('Power', 'Finland', 'Consumer Goods', 'https://www.power.fi'),
('Elisa', 'Finland', 'Consumer Goods', 'https://www.elisa.fi'),
('Telia Finland', 'Finland', 'Consumer Goods', 'https://www.telia.fi'),
('DNA', 'Finland', 'Consumer Goods', 'https://www.dna.fi'),
('Yle', 'Finland', 'Consumer Goods', 'https://www.yle.fi'),
('MTV', 'Finland', 'Consumer Goods', 'https://www.mtv.fi'),
('Sanoma', 'Finland', 'Consumer Goods', 'https://www.sanoma.fi'),
('Alma Media', 'Finland', 'Consumer Goods', 'https://www.almamedia.fi'),
('Kesko', 'Finland', 'Consumer Goods', 'https://www.kesko.fi'),

-- Healthcare
('Orion', 'Finland', 'Healthcare', 'https://www.orion.fi'),
('HUS', 'Finland', 'Healthcare', 'https://www.hus.fi'),
('Terveystalo', 'Finland', 'Healthcare', 'https://www.terveystalo.com'),
('Mehiläinen', 'Finland', 'Healthcare', 'https://www.mehilainen.fi'),
('Pihlajalinna', 'Finland', 'Healthcare', 'https://www.pihlajalinna.fi'),
('Attendo', 'Finland', 'Healthcare', 'https://www.attendo.fi'),
('Kela', 'Finland', 'Healthcare', 'https://www.kela.fi'),
('THL', 'Finland', 'Healthcare', 'https://www.thl.fi'),
('Fimea', 'Finland', 'Healthcare', 'https://www.fimea.fi'),
('Valvira', 'Finland', 'Healthcare', 'https://www.valvira.fi'),
('Orion Pharma', 'Finland', 'Healthcare', 'https://www.orion.fi'),
('HUS Helsinki', 'Finland', 'Healthcare', 'https://www.hus.fi'),
('Terveystalo Helsinki', 'Finland', 'Healthcare', 'https://www.terveystalo.fi'),
('Mehiläinen Helsinki', 'Finland', 'Healthcare', 'https://www.mehilainen.fi'),
('Pihlajalinna Helsinki', 'Finland', 'Healthcare', 'https://www.pihlajalinna.fi');

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for companies table
CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON companies
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column(); 